import invoiceAppScreenshot from "@/public/mernApp.png";
import noteAppScreenshot from "@/public/note-printscreen.png";
import meanAppScreenshot from "@/public/angular.png";
import kanbanAppScreenshot from "@/public/kanban.png"

export const projects = [
 {
  title: "Kanbaan",
  description: "ProjectsPage.kanbanApp.shortDescription",
  image: kanbanAppScreenshot,
  github: "https://github.com/lubosJurca/kanbaan_frontend",
  liveDemo: "https://kanbaan-frontend.vercel.app/",
  technologies: [
    "Angular",
    "ASP.NET Core",
    "C#",
    "PostgreSQL",
    "TypeScript",
    "Tailwind CSS",
    "Cookie Auth",
    "REST API",
    "PrimeNG",
    "NgRx Signal Store",
    "Entity Framework Core",
    "Neon",
  ],
  info: "ProjectsPage.kanbanApp.info",
  frontend: [
    "ProjectsPage.kanbanApp.frontend.p-1",
    "ProjectsPage.kanbanApp.frontend.p-2",
    "ProjectsPage.kanbanApp.frontend.p-3",
  ],
  backend: [
    "ProjectsPage.kanbanApp.backend.p-1",
    "ProjectsPage.kanbanApp.backend.p-2",
    "ProjectsPage.kanbanApp.backend.p-3",
  ],
},

  {
    title: "MEAN Invoice App",
    description: "ProjectsPage.meanApp.shortDescription",
    image: meanAppScreenshot,
    github: "https://github.com/lubosJurca/invoices-angular-frontend",
    liveDemo: "https://invoices-angular-frontend.vercel.app/",
    technologies: [
      "Angular",
      "Express.js",
      "Node.js",
      "MongoDB",
      "TypeScript",
      "Tailwind CSS",
      "JWT",
      "REST API",
      "PrimeNG",
      "RxJS",
      "Integrace AI",
      "Reactive Forms",
    ],
    info: "ProjectsPage.meanApp.info",
    frontend: [
      "ProjectsPage.meanApp.frontend.p-1",
      "ProjectsPage.meanApp.frontend.p-2",
      "ProjectsPage.meanApp.frontend.p-3",
    ],
    backend: [
      "ProjectsPage.meanApp.backend.p-1",
      "ProjectsPage.meanApp.backend.p-2",
      "ProjectsPage.meanApp.backend.p-3",
    ],
  },
  {
    title: "MERN Invoice App",
    description: "ProjectsPage.invoiceApp.shortDescription",
    image: invoiceAppScreenshot,
    github: "https://github.com/lubosJurca/MERN-Invoice",
    liveDemo: "https://mern-invoice-jkgn.onrender.com/",
    technologies: [
      "React",
      "Express.js",
      "Node.js",
      "MongoDB",
      "TypeScript",
      "Tailwind CSS",
      "JWT",
      "REST API",
      "i18next",
      "React Query",
      "Shadcn UI",
      "Zod",
      "React Hook Form",
    ],
    info: "ProjectsPage.invoiceApp.info",
    frontend: [
      "ProjectsPage.invoiceApp.frontend.p-1",
      "ProjectsPage.invoiceApp.frontend.p-2",
      "ProjectsPage.invoiceApp.frontend.p-3",
    ],
    backend: [
      "ProjectsPage.invoiceApp.backend.p-1",
      "ProjectsPage.invoiceApp.backend.p-2",
      "ProjectsPage.invoiceApp.backend.p-3",
    ],
  },
  {
    title: " Next.js Note App",
    description: "ProjectsPage.noteApp.shortDescription",
    image: noteAppScreenshot,
    github: "https://github.com/lubosJurca/Notes-app",
    liveDemo: "https://notes-app-iota-coral.vercel.app/",
    technologies: [
      "React 19",
      "Next.js 15",
      "TypeScript",
      "TanStack React Query",
      "Server Actions",
      "Prisma ORM",
      "Neon Serverless PostgreSQL",
      "Kinde Auth",
      "ShadCN UI",
      "Zod",
      "React Hook Form",
      "Next Safe Action",
    ],
    info: "ProjectsPage.noteApp.info",
    frontend: [
      "ProjectsPage.noteApp.frontend.p-1",
      "ProjectsPage.noteApp.frontend.p-2",
      "ProjectsPage.noteApp.frontend.p-3",
    ],
    backend: [
      "ProjectsPage.noteApp.backend.p-1",
      "ProjectsPage.noteApp.backend.p-2",
      "ProjectsPage.noteApp.backend.p-3",
    ],
  },
];
